package ru.manager.ProgectManager.enums;

public enum Errors {
    TOKEN_EXPIRED(1000),
    TOKEN_INVALID(1001),
    USER_WITH_THIS_LOGIN_ALREADY_CREATED(1010),
    INCORRECT_LOGIN_OR_PASSWORD(1011),
    PROJECT_ACCESS_TOKEN_IS_DEPRECATED(1020),
    PROJECT_ACCESS_TOKEN_IS_INVALID_OR_NO_LONGER_AVAILABLE(1021),
    NO_SUCH_SPECIFIED_PROJECT(1022),
    TOKEN_FOR_ACCESS_WITH_PROJECT_AS_ADMIN_MUST_BE_DISPOSABLE(1030),
    NO_SUCH_SPECIFIED_ELEMENT(1040),
    NO_SUCH_SPECIFIED_ELEMENT_OR_COLUMN(1041),
    NO_SUCH_SPECIFIED_COLUMN(1042),
    NO_SUCH_SPECIFIED_KANBAN(1043),
    NO_SUCH_SPECIFIED_USER(1050),
    INDEX_MORE_COLLECTION_SIZE(1100),
    BAD_FILE(1110);

    Errors(int value){
        numValue = value;
    }

    private final int numValue;

    public int getNumValue() {
        return numValue;
    }
}
